export const RACAS_CORES = [
  { value: 'branca', label: 'Branca' },
  { value: 'preta', label: 'Preta' },
  { value: 'parda', label: 'Parda' },
  { value: 'amarela', label: 'Amarela' },
  { value: 'indigena', label: 'Indígena' },
];

export const ESTADOS_CIVIS = [
  { value: 'solteiro', label: 'Solteiro(a)' },
  { value: 'casado', label: 'Casado(a)' },
  { value: 'divorciado', label: 'Divorciado(a)' },
  { value: 'viuvo', label: 'Viúvo(a)' },
  { value: 'uniao_estavel', label: 'União Estável' },
];

export const NATUREZAS_OCUPACAO = [
  { value: '01', label: '01 - Empregado de empresa privada, exceto de instituições financeiras' },
  { value: '02', label: '02 - Empregado de instituições financeiras privadas' },
  { value: '11', label: '11 - Servidor público da administração direta, autárquica e fundacional e empregado de empresa pública ou de sociedade de economia mista' },
  { value: '12', label: '12 - Militar' },
  { value: '21', label: '21 - Profissional liberal ou autônomo sem vínculo de emprego' },
  { value: '22', label: '22 - Proprietário de empresa ou de firma individual ou sócio-gerente' },
  { value: '31', label: '31 - Capitalista, que auferiu rendimentos de capital' },
  { value: '41', label: '41 - Aposentado, militar reformado ou reserva remunerada e pensionista de previdência' },
  { value: '51', label: '51 - Espólio' },
  { value: '61', label: '61 - Natureza de ocupação não especificada anteriormente' },
];

export const OCUPACOES_PRINCIPAIS = [
  { value: '010', label: '010 - Dirigente superior da administração pública' },
  { value: '020', label: '020 - Dirigente de organização de interesse público e de outras organizações não-governamentais' },
  { value: '030', label: '030 - Dirigente de empresa ou organização privada' },
  { value: '100', label: '100 - Profissionais das ciências exatas, físicas, químicas, engenharias e afins' },
  { value: '110', label: '110 - Engenheiro, arquiteto, agrônomo e afins' },
  { value: '120', label: '120 - Físico, químico, matemático, estatístico e afins' },
  { value: '210', label: '210 - Profissional da saúde de nível superior' },
  { value: '211', label: '211 - Médico' },
  { value: '212', label: '212 - Cirurgião-dentista' },
  { value: '213', label: '213 - Veterinário, zootecnista e afins' },
  { value: '214', label: '214 - Farmacêutico' },
  { value: '215', label: '215 - Enfermeiro de nível superior, fisioterapeuta, nutricionista e afins' },
  { value: '220', label: '220 - Profissional das ciências jurídicas, sociais e humanas' },
  { value: '221', label: '221 - Advogado' },
  { value: '222', label: '222 - Magistrado' },
  { value: '223', label: '223 - Procurador, promotor e afins' },
  { value: '225', label: '225 - Contador e auditor' },
  { value: '226', label: '226 - Economista, administrador e afins' },
  { value: '230', label: '230 - Profissional das letras, das artes e da informação' },
  { value: '231', label: '231 - Jornalista' },
  { value: '240', label: '240 - Profissional do ensino' },
  { value: '250', label: '250 - Profissional das ciências biológicas, agrárias e afins' },
  { value: '255', label: '255 - Técnico de nível médio em ciências físicas, químicas, engenharias e afins' },
  { value: '260', label: '260 - Técnico de nível médio em ciências biológicas, bioquímicas, da saúde e afins' },
  { value: '265', label: '265 - Técnico de nível médio em serviços administrativos' },
  { value: '270', label: '270 - Técnico de nível médio das artes, da cultura, do desporto e do culto' },
  { value: '310', label: '310 - Trabalhador de serviços administrativos' },
  { value: '320', label: '320 - Trabalhador de serviços de hotelaria e alimentação' },
  { value: '330', label: '330 - Trabalhador dos serviços de segurança e de proteção' },
  { value: '340', label: '340 - Vendedor e prestador de serviços do comércio' },
  { value: '350', label: '350 - Trabalhador de serviços diversos' },
  { value: '410', label: '410 - Trabalhador na exploração agropecuária' },
  { value: '510', label: '510 - Trabalhador na extração mineral' },
  { value: '610', label: '610 - Trabalhador na indústria e na construção civil' },
  { value: '710', label: '710 - Motorista de veículos a motor e afins' },
  { value: '810', label: '810 - Operador de máquinas e afins' },
  { value: '999', label: '999 - Outras ocupações não especificadas anteriormente' },
];
